name: Run shodou scanner

on:
  schedule:
    - cron: '0 0 * * *'  # UTCで毎日0時（日本時間9時）
  workflow_dispatch:      # 手動実行もできるように

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install yfinance pandas

      - name: Run script
        run: |
          python main.py
